<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<NoWarn>CS1998</NoWarn>
		<Title>EventHighway.EventHandlers</Title>
		<Authors>Hassan Habib; Christo du Toit</Authors>
		<Company>The Standard Organization</Company>
		<Product>EventHighway.EventHandlers</Product>
		<Version>2.1.0</Version>
		<AssemblyVersion>2.1.0.0</AssemblyVersion>
		<FileVersion>2.1.0.0</FileVersion>
		<PackageId>EventHighway.EventHandlers</PackageId>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Copyright>The Standard Organization 2026 (c)</Copyright>
		<PackageIcon>EventHighwayLogo.png</PackageIcon>
		<PackageLicenseFile>license.txt</PackageLicenseFile>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Description>Standard-compliant open-source .NET library containing EventHandler implementations for distributed systems, including REST API and delegate-based handlers.</Description>
		<PackageProjectUrl>https://github.com/hassanhabib/EventHighway</PackageProjectUrl>
		<RepositoryUrl>https://github.com/hassanhabib/EventHighway</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>Event-Driven</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="EventHighway.EventHandlers.Tests.Unit" />
		<InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\EventHighwayLogo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
			<Link>EventHighwayLogo.png</Link>
		</None>
		<None Include="..\license.txt">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
			<Link>license.txt</Link>
		</None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\EventHighway.Abstractions\EventHighway.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Models\Exposers\RestSecretEventHandlers\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="RESTFulSense" Version="3.2.0" />
	  <PackageReference Include="Xeption" Version="2.9.0" />
	</ItemGroup>

</Project>
