<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<NoWarn>CS1998</NoWarn>
		<Title>EventHighway</Title>
		<Authors>Hassan Habib; Christo du Toit</Authors>
		<Company>The Standard Organization</Company>
		<Product>EventHighway</Product>
		<Version>2.1.0</Version>
		<AssemblyVersion>2.1.0.0</AssemblyVersion>
		<FileVersion>2.1.0.0</FileVersion>
		<PackageId>EventHighway</PackageId>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Copyright>Hassan Habib 2026 (c)</Copyright>
		<PackageIcon>EventHighwayLogo.png</PackageIcon>
		<PackageLicenseFile>license.txt</PackageLicenseFile>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Description>Standard-Compliant Open-Source Pub/Sub .NET library for managing events in distributed systems.</Description>
		<PackageProjectUrl>https://github.com/hassanhabib/EventHighway</PackageProjectUrl>
		<RepositoryUrl>https://github.com/hassanhabib/EventHighway</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>Event-Driven</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="EFxceptions" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="DynamicExpresso.Core" Version="2.*" />
		<PackageReference Include="RESTFulSense" Version="3.2.0" />
		<PackageReference Include="STX.EFCore.Client" Version="3.0.0" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="EventHighway.Core.Tests.Unit" />
		<InternalsVisibleTo Include="EventHighway.Portal.Seed" />
		<InternalsVisibleTo Include="EventHighway.SqlServer" />
		<InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\EventHighwayLogo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
			<Link>EventHighwayLogo.png</Link>
		</None>
		<None Include="..\license.txt">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
			<Link>license.txt</Link>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Services\Foundations\EventAddresses\V2\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\EventHighway.Abstractions\EventHighway.Abstractions.csproj" />
	</ItemGroup>

</Project>
