// <auto-generated />
using System;
using EventHighway.Core.Brokers.Storages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventHighway.Core.Migrations
{
    [DbContext(typeof(StorageBroker))]
    [Migration("20260620130153_RemoveHandlerConfigurations")]
    partial class RemoveHandlerConfigurations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventAddresses.EventAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("EventAddresses", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventAddresses.V1.EventAddressV1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("EventAddressV1s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventAddresses.V2.EventAddressV2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("EventAddressV2s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventListeners.EventListener", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endpoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HeaderSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EventAddressId");

                    b.ToTable("EventListeners", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventListeners.V1.EventListenerV1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endpoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HeaderSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EventAddressId");

                    b.ToTable("EventListenerV1s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventListeners.V2.EventListenerV2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilterCriteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HandlerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HandlerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromotedProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EventAddressId");

                    b.ToTable("EventListenerV2s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.Events.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EventAddressId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.Events.V1.EventV1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RetryAttempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ScheduledDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EventAddressId");

                    b.ToTable("EventV1s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.Events.V2.EventV2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RemainingRetryAttempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ScheduledDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EventAddressId");

                    b.ToTable("EventV2s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventsArchives.V1.EventArchiveV1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ArchivedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ScheduledDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("EventV1Archives", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventsArchives.V2.EventArchiveV2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ArchivedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RemainingRetryAttempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ScheduledDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("EventArchiveV2s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.ListenerEventArchives.V1.ListenerEventArchiveV1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ArchivedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EventArchiveV1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventListenerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseReasonPhrase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EventArchiveV1Id");

                    b.ToTable("ListenerEventV1Archives", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.ListenerEventArchives.V2.ListenerEventArchiveV2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ArchivedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventArchiveV2Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventListenerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EventArchiveV2Id");

                    b.ToTable("ListenerEventArchiveV2s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.ListenerEvents.ListenerEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventListenerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EventAddressId");

                    b.HasIndex("EventId");

                    b.HasIndex("EventListenerId");

                    b.ToTable("ListenerEvents", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.ListenerEvents.V1.ListenerEventV1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventListenerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseReasonPhrase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EventAddressId");

                    b.HasIndex("EventId");

                    b.HasIndex("EventListenerId");

                    b.ToTable("ListenerEventV1s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.ListenerEvents.V2.ListenerEventV2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventListenerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EventAddressId");

                    b.HasIndex("EventId");

                    b.HasIndex("EventListenerId");

                    b.ToTable("ListenerEventV2s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventListeners.EventListener", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventAddresses.EventAddress", "EventAddress")
                        .WithMany("EventListeners")
                        .HasForeignKey("EventAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EventAddress");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventListeners.V1.EventListenerV1", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventAddresses.V1.EventAddressV1", "EventAddress")
                        .WithMany("EventListeners")
                        .HasForeignKey("EventAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EventAddress");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventListeners.V2.EventListenerV2", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventAddresses.V2.EventAddressV2", "EventAddressV2")
                        .WithMany("EventListenerV2s")
                        .HasForeignKey("EventAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EventAddressV2");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.Events.Event", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventAddresses.EventAddress", "EventAddress")
                        .WithMany("Events")
                        .HasForeignKey("EventAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EventAddress");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.Events.V1.EventV1", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventAddresses.V1.EventAddressV1", "EventAddress")
                        .WithMany("Events")
                        .HasForeignKey("EventAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EventAddress");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.Events.V2.EventV2", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventAddresses.V2.EventAddressV2", "EventAddressV2")
                        .WithMany("Events")
                        .HasForeignKey("EventAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EventAddressV2");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.ListenerEventArchives.V1.ListenerEventArchiveV1", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventsArchives.V1.EventArchiveV1", null)
                        .WithMany("ListenerEventArchiveV1s")
                        .HasForeignKey("EventArchiveV1Id");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.ListenerEventArchives.V2.ListenerEventArchiveV2", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventsArchives.V2.EventArchiveV2", null)
                        .WithMany("ListenerEventArchiveV2s")
                        .HasForeignKey("EventArchiveV2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.ListenerEvents.ListenerEvent", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventAddresses.EventAddress", "EventAddress")
                        .WithMany("ListenerEvents")
                        .HasForeignKey("EventAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EventHighway.Core.Models.Services.Foundations.Events.Event", "Event")
                        .WithMany("ListenerEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventListeners.EventListener", "EventListener")
                        .WithMany("ListenerEvents")
                        .HasForeignKey("EventListenerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("EventAddress");

                    b.Navigation("EventListener");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.ListenerEvents.V1.ListenerEventV1", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventAddresses.V1.EventAddressV1", "EventAddress")
                        .WithMany("ListenerEvents")
                        .HasForeignKey("EventAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EventHighway.Core.Models.Services.Foundations.Events.V1.EventV1", "Event")
                        .WithMany("ListenerEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventListeners.V1.EventListenerV1", "EventListener")
                        .WithMany("ListenerEvents")
                        .HasForeignKey("EventListenerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("EventAddress");

                    b.Navigation("EventListener");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.ListenerEvents.V2.ListenerEventV2", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventAddresses.V2.EventAddressV2", "EventAddress")
                        .WithMany("ListenerEventV2s")
                        .HasForeignKey("EventAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EventHighway.Core.Models.Services.Foundations.Events.V2.EventV2", "Event")
                        .WithMany("ListenerEventV2s")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventListeners.V2.EventListenerV2", "EventListener")
                        .WithMany("ListenerEventV2s")
                        .HasForeignKey("EventListenerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("EventAddress");

                    b.Navigation("EventListener");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventAddresses.EventAddress", b =>
                {
                    b.Navigation("EventListeners");

                    b.Navigation("Events");

                    b.Navigation("ListenerEvents");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventAddresses.V1.EventAddressV1", b =>
                {
                    b.Navigation("EventListeners");

                    b.Navigation("Events");

                    b.Navigation("ListenerEvents");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventAddresses.V2.EventAddressV2", b =>
                {
                    b.Navigation("EventListenerV2s");

                    b.Navigation("Events");

                    b.Navigation("ListenerEventV2s");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventListeners.EventListener", b =>
                {
                    b.Navigation("ListenerEvents");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventListeners.V1.EventListenerV1", b =>
                {
                    b.Navigation("ListenerEvents");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventListeners.V2.EventListenerV2", b =>
                {
                    b.Navigation("ListenerEventV2s");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.Events.Event", b =>
                {
                    b.Navigation("ListenerEvents");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.Events.V1.EventV1", b =>
                {
                    b.Navigation("ListenerEvents");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.Events.V2.EventV2", b =>
                {
                    b.Navigation("ListenerEventV2s");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventsArchives.V1.EventArchiveV1", b =>
                {
                    b.Navigation("ListenerEventArchiveV1s");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventsArchives.V2.EventArchiveV2", b =>
                {
                    b.Navigation("ListenerEventArchiveV2s");
                });
#pragma warning restore 612, 618
        }
    }
}
