// <auto-generated />
using System;
using EventHighway.Core.Brokers.Storages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventHighway.PostgreSql.Migrations
{
    [DbContext(typeof(StorageBroker))]
    partial class StorageBrokerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventAddresses.EventAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.ToTable("EventAddresses", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventAddresses.V1.EventAddressV1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.ToTable("EventAddressV1s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventAddresses.V2.EventAddressV2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EventAddressV2s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventHandler.V2.EventHandlerV2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EventHandlerV2s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventListeners.EventListener", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Endpoint")
                        .HasColumnType("text");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uuid");

                    b.Property<string>("HeaderSecret")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("EventAddressId");

                    b.ToTable("EventListeners", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventListeners.V1.EventListenerV1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Endpoint")
                        .HasColumnType("text");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uuid");

                    b.Property<string>("HeaderSecret")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("EventAddressId");

                    b.ToTable("EventListenerV1s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventListeners.V2.EventListenerV2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EventAddressV2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventParticipantV2Id")
                        .HasColumnType("uuid");

                    b.Property<string>("FilterCriteria")
                        .HasColumnType("text");

                    b.Property<Guid>("HandlerId")
                        .HasColumnType("uuid");

                    b.Property<string>("HandlerName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("PromotedProperties")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("EventAddressV2Id");

                    b.HasIndex("EventParticipantV2Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EventListenerV2s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventParticipants.V2.EventParticipantSecretV2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("EventParticipantV2Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Secret")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("EventParticipantV2Id");

                    b.HasIndex("Id", "Secret")
                        .IsUnique();

                    b.ToTable("EventParticipantSecretV2s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventParticipants.V2.EventParticipantV2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.ToTable("EventParticipantV2s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.Events.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("EventAddressId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.Events.V1.EventV1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uuid");

                    b.Property<int>("RetryAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ScheduledDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("EventAddressId");

                    b.ToTable("EventV1s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.Events.V2.EventV2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("EventAddressV2Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EventName")
                        .HasColumnType("text");

                    b.Property<Guid?>("EventParticipantV2Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ScheduledDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("IX_EventV2s_CreatedDate")
                        .HasAnnotation("SqlServer:Include", new[] { "Type" });

                    b.HasIndex("EventParticipantV2Id");

                    b.HasIndex("EventAddressV2Id", "CreatedDate")
                        .HasDatabaseName("IX_EventV2s_AddressCreatedDate")
                        .HasAnnotation("SqlServer:Include", new[] { "Status", "Type", "EventParticipantV2Id" });

                    b.HasIndex("Status", "Type")
                        .HasDatabaseName("IX_EventV2s_StatusType");

                    b.HasIndex("EventAddressV2Id", "EventName", "ContentHash", "CreatedDate")
                        .HasDatabaseName("IX_EventV2s_LoopDetection");

                    b.ToTable("EventV2s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventsArchives.V1.EventArchiveV1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ArchivedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ScheduledDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.ToTable("EventV1Archives", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventsArchives.V2.EventArchiveV2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ArchivedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("EventAddressV2Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EventName")
                        .HasColumnType("text");

                    b.Property<Guid?>("EventParticipantV2Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ScheduledDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedDate")
                        .HasDatabaseName("IX_EventArchiveV2s_ArchivedDate");

                    b.HasIndex("EventParticipantV2Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_EventArchiveV2s_Status");

                    b.HasIndex("EventAddressV2Id", "ArchivedDate")
                        .HasDatabaseName("IX_EventArchiveV2s_AddressArchivedDate")
                        .HasAnnotation("SqlServer:Include", new[] { "Status" });

                    b.HasIndex("EventAddressV2Id", "ContentHash")
                        .HasDatabaseName("IX_EventArchiveV2s_ContentHash");

                    b.ToTable("EventArchiveV2s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.ListenerEventArchives.V1.ListenerEventArchiveV1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ArchivedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventArchiveV1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventListenerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<string>("ResponseReasonPhrase")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("EventArchiveV1Id");

                    b.ToTable("ListenerEventV1Archives", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.ListenerEventArchives.V2.ListenerEventArchiveV2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ArchivedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("DispatchedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("EventAddressV2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventArchiveV2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventListenerV2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventParticipantV2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventV2Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("NextRetryAttemptNotBefore")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<int>("RemainingRetryAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<string>("ResponseCode")
                        .HasColumnType("text");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("text");

                    b.Property<int>("RetryAttemptsAllowed")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedDate")
                        .HasDatabaseName("IX_ListenerEventArchiveV2s_ArchivedDate")
                        .HasAnnotation("SqlServer:Include", new[] { "Status" });

                    b.HasIndex("EventArchiveV2Id");

                    b.HasIndex("EventListenerV2Id");

                    b.HasIndex("EventParticipantV2Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ListenerEventArchiveV2s_Status");

                    b.HasIndex("EventAddressV2Id", "ArchivedDate")
                        .HasDatabaseName("IX_ListenerEventArchiveV2s_AddressArchivedDate")
                        .HasAnnotation("SqlServer:Include", new[] { "Status" });

                    b.HasIndex("Status", "RemainingRetryAttempts")
                        .HasDatabaseName("IX_ListenerEventArchiveV2s_RetryClassification");

                    b.ToTable("ListenerEventArchiveV2s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.ListenerEvents.ListenerEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventListenerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("EventAddressId");

                    b.HasIndex("EventId");

                    b.HasIndex("EventListenerId");

                    b.ToTable("ListenerEvents", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.ListenerEvents.V1.ListenerEventV1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("EventAddressId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventListenerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<string>("ResponseReasonPhrase")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("EventAddressId");

                    b.HasIndex("EventId");

                    b.HasIndex("EventListenerId");

                    b.ToTable("ListenerEventV1s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.ListenerEvents.V2.ListenerEventV2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("DispatchedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("EventAddressV2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventListenerV2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventParticipantV2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventV2Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("NextRetryAttemptNotBefore")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.Property<int>("RemainingRetryAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<string>("ResponseCode")
                        .HasColumnType("text");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("text");

                    b.Property<int>("RetryAttemptsAllowed")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasPrecision(6)
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("IX_ListenerEventV2s_CreatedDate")
                        .HasAnnotation("SqlServer:Include", new[] { "Status" });

                    b.HasIndex("EventListenerV2Id");

                    b.HasIndex("EventParticipantV2Id");

                    b.HasIndex("EventV2Id")
                        .HasDatabaseName("IX_ListenerEventV2s_ToBeArchived")
                        .HasAnnotation("SqlServer:Include", new[] { "Status", "RemainingRetryAttempts", "DispatchedDate" });

                    b.HasIndex("EventAddressV2Id", "CreatedDate")
                        .HasDatabaseName("IX_ListenerEventV2s_AddressCreatedDate")
                        .HasAnnotation("SqlServer:Include", new[] { "Status", "RemainingRetryAttempts" });

                    b.HasIndex("Status", "RemainingRetryAttempts")
                        .HasDatabaseName("IX_ListenerEventV2s_RetryClassification");

                    b.ToTable("ListenerEventV2s", (string)null);
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventListeners.EventListener", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventAddresses.EventAddress", "EventAddress")
                        .WithMany("EventListeners")
                        .HasForeignKey("EventAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EventAddress");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventListeners.V1.EventListenerV1", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventAddresses.V1.EventAddressV1", "EventAddress")
                        .WithMany("EventListeners")
                        .HasForeignKey("EventAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EventAddress");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventListeners.V2.EventListenerV2", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventAddresses.V2.EventAddressV2", "EventAddressV2")
                        .WithMany("EventListenerV2s")
                        .HasForeignKey("EventAddressV2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventParticipants.V2.EventParticipantV2", "EventParticipantV2")
                        .WithMany("EventListenerV2s")
                        .HasForeignKey("EventParticipantV2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EventAddressV2");

                    b.Navigation("EventParticipantV2");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventParticipants.V2.EventParticipantSecretV2", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventParticipants.V2.EventParticipantV2", "EventParticipantV2")
                        .WithMany("EventParticipantSecretV2s")
                        .HasForeignKey("EventParticipantV2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventParticipantV2");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.Events.Event", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventAddresses.EventAddress", "EventAddress")
                        .WithMany("Events")
                        .HasForeignKey("EventAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EventAddress");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.Events.V1.EventV1", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventAddresses.V1.EventAddressV1", "EventAddress")
                        .WithMany("Events")
                        .HasForeignKey("EventAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EventAddress");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.Events.V2.EventV2", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventAddresses.V2.EventAddressV2", "EventAddressV2")
                        .WithMany("EventV2s")
                        .HasForeignKey("EventAddressV2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventParticipants.V2.EventParticipantV2", "EventParticipantV2")
                        .WithMany("EventV2s")
                        .HasForeignKey("EventParticipantV2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EventAddressV2");

                    b.Navigation("EventParticipantV2");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventsArchives.V2.EventArchiveV2", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventAddresses.V2.EventAddressV2", "EventAddressV2")
                        .WithMany("EventArchiveV2s")
                        .HasForeignKey("EventAddressV2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventParticipants.V2.EventParticipantV2", "EventParticipantV2")
                        .WithMany("EventArchiveV2s")
                        .HasForeignKey("EventParticipantV2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EventAddressV2");

                    b.Navigation("EventParticipantV2");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.ListenerEventArchives.V1.ListenerEventArchiveV1", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventsArchives.V1.EventArchiveV1", null)
                        .WithMany("ListenerEventArchiveV1s")
                        .HasForeignKey("EventArchiveV1Id");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.ListenerEventArchives.V2.ListenerEventArchiveV2", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventsArchives.V2.EventArchiveV2", null)
                        .WithMany("ListenerEventArchiveV2s")
                        .HasForeignKey("EventArchiveV2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventListeners.V2.EventListenerV2", "EventListenerV2")
                        .WithMany("ListenerEventArchiveV2s")
                        .HasForeignKey("EventListenerV2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventParticipants.V2.EventParticipantV2", "EventParticipantV2")
                        .WithMany("ListenerEventArchiveV2s")
                        .HasForeignKey("EventParticipantV2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EventListenerV2");

                    b.Navigation("EventParticipantV2");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.ListenerEvents.ListenerEvent", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventAddresses.EventAddress", "EventAddress")
                        .WithMany("ListenerEvents")
                        .HasForeignKey("EventAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EventHighway.Core.Models.Services.Foundations.Events.Event", "Event")
                        .WithMany("ListenerEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventListeners.EventListener", "EventListener")
                        .WithMany("ListenerEvents")
                        .HasForeignKey("EventListenerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("EventAddress");

                    b.Navigation("EventListener");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.ListenerEvents.V1.ListenerEventV1", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventAddresses.V1.EventAddressV1", "EventAddress")
                        .WithMany("ListenerEvents")
                        .HasForeignKey("EventAddressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EventHighway.Core.Models.Services.Foundations.Events.V1.EventV1", "Event")
                        .WithMany("ListenerEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventListeners.V1.EventListenerV1", "EventListener")
                        .WithMany("ListenerEvents")
                        .HasForeignKey("EventListenerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("EventAddress");

                    b.Navigation("EventListener");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.ListenerEvents.V2.ListenerEventV2", b =>
                {
                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventAddresses.V2.EventAddressV2", "EventAddressV2")
                        .WithMany("ListenerEventV2s")
                        .HasForeignKey("EventAddressV2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventListeners.V2.EventListenerV2", "EventListenerV2")
                        .WithMany("ListenerEventV2s")
                        .HasForeignKey("EventListenerV2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventHighway.Core.Models.Services.Foundations.EventParticipants.V2.EventParticipantV2", "EventParticipantV2")
                        .WithMany("ListenerEventV2s")
                        .HasForeignKey("EventParticipantV2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EventHighway.Core.Models.Services.Foundations.Events.V2.EventV2", "EventV2")
                        .WithMany("ListenerEventV2s")
                        .HasForeignKey("EventV2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventAddressV2");

                    b.Navigation("EventListenerV2");

                    b.Navigation("EventParticipantV2");

                    b.Navigation("EventV2");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventAddresses.EventAddress", b =>
                {
                    b.Navigation("EventListeners");

                    b.Navigation("Events");

                    b.Navigation("ListenerEvents");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventAddresses.V1.EventAddressV1", b =>
                {
                    b.Navigation("EventListeners");

                    b.Navigation("Events");

                    b.Navigation("ListenerEvents");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventAddresses.V2.EventAddressV2", b =>
                {
                    b.Navigation("EventArchiveV2s");

                    b.Navigation("EventListenerV2s");

                    b.Navigation("EventV2s");

                    b.Navigation("ListenerEventV2s");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventListeners.EventListener", b =>
                {
                    b.Navigation("ListenerEvents");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventListeners.V1.EventListenerV1", b =>
                {
                    b.Navigation("ListenerEvents");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventListeners.V2.EventListenerV2", b =>
                {
                    b.Navigation("ListenerEventArchiveV2s");

                    b.Navigation("ListenerEventV2s");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventParticipants.V2.EventParticipantV2", b =>
                {
                    b.Navigation("EventArchiveV2s");

                    b.Navigation("EventListenerV2s");

                    b.Navigation("EventParticipantSecretV2s");

                    b.Navigation("EventV2s");

                    b.Navigation("ListenerEventArchiveV2s");

                    b.Navigation("ListenerEventV2s");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.Events.Event", b =>
                {
                    b.Navigation("ListenerEvents");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.Events.V1.EventV1", b =>
                {
                    b.Navigation("ListenerEvents");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.Events.V2.EventV2", b =>
                {
                    b.Navigation("ListenerEventV2s");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventsArchives.V1.EventArchiveV1", b =>
                {
                    b.Navigation("ListenerEventArchiveV1s");
                });

            modelBuilder.Entity("EventHighway.Core.Models.Services.Foundations.EventsArchives.V2.EventArchiveV2", b =>
                {
                    b.Navigation("ListenerEventArchiveV2s");
                });
#pragma warning restore 612, 618
        }
    }
}
